name: Build OpenStick kernel

on:
  workflow_dispatch:
    inputs:
          debug_enabled:
            type: boolean
            description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
            required: false
            default: false
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Install dependencies
        run:
          sudo sh -e config/0_installdeps.sh

      - name: Install dependencies 1
        run:
          docker build --tag openstick .
          
      - name: build kernel
        run: docker run --privileged -v $(pwd)/config:/config:ro -v $(pwd)/output:/output openstick /bin/bash /config/1_kernel.sh

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true

      - name: build kernel1
        run: docker run --privileged -v $(pwd)/config:/config:ro -v $(pwd)/output:/output openstick /bin/bash /config/1_kernel_1.sh
        
      - name: build rootfs
        run: sudo sh -e config/2_rootfs.sh 
         
      - name: provision_0 img
        run: sudo sh -e config/3_provision_0.sh    
        
      - name: provision img
        run: docker run --privileged -v $(pwd)/config:/config:ro -v $(pwd)/output:/output openstick /bin/bash /config/3_provision.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openstick-debian
          path: output/*
